### ISSUE TITLE
Miniflux - Can't connect to the postgres database in the miniflux-postgres container

### ISSUE THREAD

**Issue by darioceccoli** [davestephens/ansible-nas#367] opened 2020-12-05 00:22 UTC
**Describe the bug**
Miniflux (http://ansible_nas_host_or_ip:8070) doesn't work because it fails to connect to the `miniflux-postgres` container aliased as `db`.

**Environment**
- Ansible-NAS revision (`git rev-parse --short HEAD`): 85203e2
- Ansible version (paste the entire output of `ansible --version` on the machine you run the playbook from): 2.9.15
- Ansible-NAS operating system (`cat /etc/lsb-release` on the Ansible-NAS box) - _If this is anything other than Ubuntu 18.04 help will be limited_: Ubuntu 18.04.5 LTS
- Ansible-NAS kernel (`uname -a` on the Ansible-NAS box): Linux ansible-nas 4.15.0-126-generic #129-Ubuntu SMP Mon Nov 23 18:53:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Ansible-NAS Python version (`python --version` on the Ansible-NAS box): Python 2.7.17
- Ansible-NAS Docker version (`docker --version` on the Ansible-NAS box): 19.03.14, build 5eb3275d40
- Latest Docker logs (`journalctl -u docker.service` on the Ansible-NAS box):
- Are you running the playbook from a remote box or the Ansible-NAS box itself? Running from Ansible-NAS box itself
- Vagrant version, if testing (`vagrant --version`): Vagrant not installed
- Ansible-NAS filesystems (`df -hT` on the Ansible-NAS box):
- Mounted filesystems (`mount` on the Ansible-NAS box)

**all.yml Variables**
- `docker_image_directory`:
- `docker_home`:
- `docker_storage_driver`:
- `samba_shares_root`:

**Expected behavior**
What should happen? 
`miniflux` container's logs  should show the db migrations to complete correctly and I should be able to access miniflux via http://ANSIBLE_NAS IP:8070

**Actual behavior**
What actually happens?

This is the log from the `miniflux` container
```
Current schema version: 0
Latest schema version: 40
Migrating to version: 1
[FATAL] [Migrate] dial tcp 92.242.132.24:5432: connect: connection timed out
Current schema version: 0
Latest schema version: 40
Migrating to version: 1
[FATAL] [Migrate] dial tcp 92.242.132.24:5432: connect: connection timed out
```

**Steps to reproduce**
What does someone need to do to reproduce this?
Set `miniflux_enabled: true` in your inventories/<your_inventory>/nas.yml file.
Try to access http://ansible_nas_host_or_ip:8070, the service is unavailable

**Playbook Output**
Paste the output of the playbook at the problematic point. Surround it in triple backticks so that it's formatted correctly.

**Additional context**

If I temporarily replace in the `DATABASE_URL` the `db` host with the ip of the `miniflux-postgres` container, the db migrations complete successfully and I can successfully access the Miniflux web UI.

Doesn't work:
postgres://miniflux:supersecure@db/miniflux?sslmode=disable

It works:
postgres://miniflux:supersecure@172.17.0.11/miniflux?sslmode=disable

I see the `db` hosts is in `/etc/hosts` but for some reason it doesn't get resolved.

If I `docker exec -it <CONTAINER ID> sh` and then `ping db` I get a `ping: permission denied (are you root?)` error.

**Comment by davestephens** [comment] 2021-01-16 11:39
I can't reproduce this, I've just tested and miniflux spins up fine. I think there's something odd with your DNS resolution going on here - the db alias is resolving to an external IP rather than the contain IP (as you mention). I'm assuming this is something related to your personal setup, so will close unless you can provide more info and/or a reproducible case.

**Closed by davestephens** 2021-01-16 11:39 UTC
Labels: bug
