### ISSUE TITLE
Jellyfin(Emby Open Source Clone) plugin request

### ISSUE THREAD

**Issue by ThoreauHenry** [davestephens/ansible-nas#134] opened 2019-09-22 04:25 UTC
A simple request, when you can get around to it.  Could you take a look at Jellyfin and see if it's in a mature enough state to import as a plugin.  Thank you.

https://github.com/jellyfin/jellyfin

Some background on it.

https://youtu.be/QuNLbAtMFsk

**Comment by CherryKitten** [comment] 2019-09-26 13:24
There already is a pull request for this at #123

**Comment by bcurran3** [comment] 2019-10-15 07:23
@ThoreauHenry - see https://github.com/davestephens/ansible-nas/issues/70. You might want to upvote that one and close this one as a duplicate. :)

**Comment by davestephens** [comment] 2019-10-15 14:25
Closing, dupe of #70

**Closed by davestephens** 2019-10-15 14:25 UTC
Labels: duplicate
